// lib/ai_kb.ts
export const KB: Record<string, string> = {
  // --- EVS entries ---
  "Transport": "Imagine reaching school by crossing a river on a bamboo bridge or a trolley! In India, children use many creative ways to travel. Transport isn't just about wheels; it's about the mission to learn! 🎋",
  "Animal Ears": "Why does an elephant have fan-like ears and a rabbit have long ones? Ears are nature's sensors! Some animals have hidden ears, while others use them to stay cool in the heat. 🐘",
  "Elephants": "Elephants are the gentle giants of the forest. They live in big families called herds, led by the oldest and wisest female. Did you know a baby elephant can walk just hours after being born? 🐘",
  "Trees": "Trees are our oldest friends. The Khejadi tree in Rajasthan can grow in the desert with very little water. People like Amrita Devi even gave their lives to protect them! 🌳",
  "Beekeeping": "Honeybees are tiny workers with a big job! They live in colonies with a Queen bee and thousands of workers. Anita Khushwaha showed us how we can care for bees and collect sweet honey. 🐝",
  "Train Trip": "A train journey is like a moving window into the world! From checking tickets and PNR numbers to seeing different landscapes, every mile tells a story of travel and adventure. 🚂",
  "Bridges & Tunnels": "When a train travels through mountains, it goes through dark tunnels and over high bridges. Goa alone has over 2,000 bridges and 92 tunnels on the train route! 🌉",
  "Water Transport": "In places like Kerala, water is like a road. People use small wooden boats called 'Vallams' and bigger ferries to cross rivers and reach their destinations. 🛶",
  "Family": "Families are like the branches of a tree — they grow in different directions but the roots remain the same. Families change when a new baby is born or someone gets married! 👨‍👩‍👧‍👦",
  "Kabaddi": "Kabaddi is a game of breath, strength, and teamwork! You have to chant 'Kabaddi-Kabaddi' in one breath and tag your opponents. It's a traditional sport that India loves! 🏆",
  "Plants": "Plants are the world's natural painters. From the Valley of Flowers in Uttarakhand to the herbs in our kitchen, plants give us food, medicine, and beauty. 🌸",
  "Houses": "Houses change over time. Long ago, people used mud and straw; now we use cement and steel. A house is more than just walls; it's a place where we feel safe and happy. 🏠",
  "Rivers": "A river starts in the mountains and travels to the sea. Along the way, it helps plants grow, but it also faces pollution from factories. We must protect our rivers to save life! 🌊",
  "Farming": "Farming starts with preparing the soil and ends with a harvest. Tools like the Khunti and Kurige help farmers like Basva grow healthy onions in the field. 🚜",
  "Vegetables": "Vegetables travel a long way from the mandi to your plate. Some stay fresh for days, while others need to be eaten quickly. They are the fuel that keeps our bodies strong! 🥗",
  "Birds": "Birds are nature's architects. From the Tailor Bird that sews leaves to the Weaver Bird that weaves intricate nests, every bird has a unique way of building a home. 🐦",
  "City Life": "Living in a big city like Mumbai is very different from village life. There are tall buildings, crowded trains, and many different types of houses and jobs. 🏙️",
  "Water Quality": "Not all water is safe to drink. Dirty water can cause diseases like diarrhea. Learning how to clean water and protect ourselves is a vital health skill! 💧",
  "Roots": "Roots are the hidden anchors of a plant. Some roots like carrots store food, while others like the Banyan's aerial roots grow from branches to support the tree! 🌳",
  "Festivals": "Festivals like Bihu in Assam are times to eat together and celebrate the harvest. They bring the community together with music, dance, and special food like Cheva rice. 🍚",
  "Langar": "In a Gurudwara, everyone sits together on the floor to eat a free meal called Langar. It teaches us the value of service, equality, and sharing with others. 🍛",
  "Values": "The world in our home teaches us big values. Being honest, even in small things like returning extra money, makes us strong and trusted people. 🌟",
  "Weaving": "Pochampalli weaving is a traditional art from Telangana. It takes days of hard work to weave beautiful patterns into sarees. We must respect and support our local craftsmen! 🧵",
  "Climate": "Different parts of the world have different climates. While India has many seasons, places like Abu Dhabi are hot deserts where water is more expensive than petrol! 🏜️",
  "Spices": "Spices are the magic ingredients in our food. Turmeric heals wounds, cloves soothe toothaches, and cumin helps digestion. India is the spice garden of the world! 🌶️",
  "Bravery": "Wahida Prism, a naval doctor, showed us that bravery has no gender. She was the first woman to lead a parade, proving that hard work leads to great success. ⚓",
  "Inclusion": "Chuskit's story in Ladakh teaches us about empathy. By building a ramp and a bridge, the community helped a girl in a wheelchair reach school for the first time. ♿",

  // --- Math entries ---
  "Patterns": "A brick is like a LEGO piece of history! By arranging them in different ways, we can create beautiful 'Jaali' patterns that let in light and air. Bricks are the building blocks of civilizations. 🧱",
  "Measurement": "Measurement is how we compare the world! From the length of a tiny ant in millimetres to the distance between cities in kilometres, we use different units to understand 'How Long' or 'How Far'. 📏",
  "Estimation": "Estimation is like using your 'Math Eyes' to guess! Before we count exactly, we guess how many people are on a bus or how long a trip will take. It's a superpower for planning adventures! 🗺️",
  "Time": "Time is a never-ending circle! Every 'Tick' of the clock is a second, and every 60 'Ticks' is a minute. Learning to read the clock helps us catch trains and arrive on time for school. ⏰",
  "Perspective": "The world looks different depending on where you stand! A chair looks like four legs from the side, but just a square from the top. Changing your perspective helps you understand the true shape of things. 👁️",
  "Money": "Money is a tool for sharing and trading. By learning to add up notes and coins, we can become smart shopkeepers and even smarter customers. Every rupee tells a story of work and value! 💰",
  "Capacity": "Capacity is the 'Room' inside a container. A tiny mug holds a little, but a giant jug holds a lot! We measure liquids in Litres and Millilitres to make sure we have exactly enough. 🍶",
  "Geometry": "Geometry is the study of shapes and circles. From the perfect roundness of a wheel (the Circumference) to the point in the middle (the Centre), shapes are everywhere in nature and machines! 🎡",
  "Fractions": "A Fraction is just a 'Piece of the Whole'. When we cut a pizza into Halves or Quarters, we are using math to share fairly. Half of a half is a quarter — it's like a math puzzle! 🍕",
  "Sequences": "Patterns are the 'Music' of math. They are sequences that repeat and grow. From the design on your shirt to the numbers in a sequence, finding the rule is the secret to solving the pattern! 🌈",
  "Operations": "Operations like Multiplication and Division are shortcuts for counting. Instead of adding 5+5+5, we can just say 5 times 3! It's how we share a big box of chocolates among friends. 🍫",
  "Weight": "Weight is how hard the Earth pulls on an object. A feather is light, but an elephant is heavy! We use grams and kilograms to measure the 'Heaviness' of everything from sugar to school bags. ⚖️",
  "Perimeter": "Perimeter is the 'Fence' around a shape. If you walk all the way around a field, the total distance you walk is its perimeter. It's how farmers know how much wire they need for a fence! 🚜",
  "Data": "Data is information collected into 'Smart Charts'. By using Tally Marks and Bar Graphs, we can see at a glance which fruit is the class favorite or how many students are present. 📊",

  // --- Computer Science entries ---
  "Know Your Computer": "Imagine a machine that can do your homework, play movies, and help you talk to friends across the ocean — all at once! That's a computer. It's not just a box; it's a super-helper that uses electricity to think. 💻",
  "Basics": "A computer has two main parts: the things you can kick (Hardware) and the things you can only see (Software). The CPU is the 'Brain', the Monitor is the 'Face', and the Keyboard is how you 'Talk' to it. 🧠",
  "Hardware & Software": "If a computer were a person, Hardware would be its body and Software would be its thoughts. You can touch the body, but you can only see the thoughts in action! 💿",
  "Input and Output": "Computers have 'Senses' just like you! A Mouse and Keyboard are its eyes and ears (Input), while a Monitor and Printer are its mouth and hands (Output). It's a perfect loop of information! 🖱️",
  "Devices": "Think of a Scanner as a computer's eye that reads paper, and a Speaker as its voice that sings. Every device has a special job to help the computer understand the world. 🔊",
  "Windows Basics": "Windows is the 'Digital House' where your apps live. The Desktop is your table, the Taskbar is your tool-belt, and the Start Button is the front door to everything! 🏠",
  "Desktop": "The Desktop is your main workspace. You can keep your 'Icons' (which are like shortcut keys) and beautiful 'Wallpapers' here. It's the starting point of every digital adventure! 🖼️",
  "MS Word Intro": "MS Word is a 'Magic Typewriter'. You can type a letter and suddenly change its color, make it giant, or even add a picture of a cat! It's the best place to become a digital author. ✍️",
  "Typing": "Typing is like playing a piano with letters! In MS Word, you use the 'Font' tools to change how your words look — making them bold for importance or italic for style. ⌨️",
  "Internet Safety": "The Internet is a giant global playground, but we must be careful! Treat your 'Privacy' like a secret treasure — never tell strangers your name, address, or password. 🛡️",
  "Online Rules": "Being a good 'Digital Citizen' means being kind online, just like you are in school. Always ask an adult before clicking on strange links or sharing your photo. 🕵️",
  "Algorithms": "An Algorithm is just a 'Secret Map' to solve a problem! It's a list of steps like: 1. Get bread, 2. Add jam, 3. Eat! If you miss a step, the computer gets confused. 🥪",
  "Coding Basics": "Coding is the language we use to talk to robots. By giving them clear steps (Algorithms), we can make them dance, draw, or even fly a spaceship! 🚀",
  "MS Paint Mastery": "MS Paint is a 'Bucket of Digital Light'! You can use the shapes to build a castle and the 'Fill' tool to splash a rainbow onto your drawing with just one click. 🎨",
  "Drawing": "In digital drawing, you don't need to worry about messy colors! Use the 'Shapes' tool to make perfect circles and the 'Pencil' tool to sketch your dreams on the screen. 🖌️",
  "PowerPoint Basics": "PowerPoint is your 'Digital Stage'. Each 'Slide' is like a page in a moving storybook. You can add 'Animations' to make your pictures fly in and 'Transitions' to slide from one idea to the next! 📊",
  "Presentations": "A presentation is how you show your big ideas to the class! Use PowerPoint to create beautiful slides that catch everyone's eye and tell your story with pictures and movement. 🎤",
  "Scratch Jr. Intro": "Scratch Jr. is a 'Lego set for Coding'. You snap blocks together to make characters walk, talk, and jump. It's the first step to making your very own video game! 🤖",
  "Visual Coding": "Visual coding uses colorful blocks instead of typing. It's like building a puzzle — when the pieces fit, your character comes to life and follows your commands! 🧩",
  "Email & Communication": "An Email is a 'Digital Paper Plane' that carries your message across the world in a blink. It uses the '@' symbol to find the right digital mailbox! 📧",
  "Internet": "The Internet is a giant web connecting every computer on Earth. It lets us share emails, watch videos, and learn new things from people thousands of miles away! 🌐",

  // --- English entries ---
  "Poem": "Poems are like songs without music! They use rhythm and rhyme to paint pictures in your mind. From the waking sun to the croak of a frog, every poem is a window into a beautiful world. 📖",
  "Funny Noses": "Have you ever looked in the mirror and laughed at your own nose? Nature gives every animal a special nose for a special job — some for smelling, some for breathing, and some just for looking funny! 👃",
  "Exercise": "Running and jumping are the fuel for a healthy body. When you run away from the city and into the green fields, your heart dances and your lungs sing with fresh air! 🏃",
  "Curiosity": "Being curious is the first step to becoming a scientist. Asking 'Why?' helps us understand why the sun shines, why the wind blows, and how the world works. 🔍",
  "Courage": "Courage isn't just about fighting; it's about never giving up. Helen Keller showed us that even if we can't see or hear, we can still learn to talk and change the world with our hearts. 🌟",
  "Nature": "Hiawatha learned the secrets of every bird and beast. He called them his 'Brothers' because in nature, everything is connected. Learning the language of animals is the greatest magic! 🦊",
  "Generosity": "The Giving Tree teaches us that the greatest joy comes from sharing. Nature gives us everything — shade, fruit, and wood — and asks for nothing but love in return. 🌳",
  "Reading": "A library is a treasure chest of stories! Every book you open is a new world waiting to be explored. Once you start reading, you can travel anywhere without ever leaving your chair. 📚",
  "Honesty": "Pinocchio's growing nose is a reminder that truth is the best path. When we are honest, our hearts are light and we don't have to hide behind tall tales. 🤥",
  "Strange Talk (Poem)": "If a frog said 'Croak' and a pig said 'Wee', the world would be a very noisy place! Language is how we share our feelings, and every animal has its own special way of talking. 🐸",
  "The Grasshopper and the Ant": "The Ant knows that hard work today leads to a happy tomorrow. While the Grasshopper sang, the Ant prepared. It's a lesson in planning and being responsible for our future. 🐜",

  // --- Hindi entries ---
  "कविता": "कविता शब्दों का जादू है! लय और तुकबंदी के साथ हम अपनी भावनाओं को व्यक्त करते हैं। बादलों के हाथी-घोड़े हों या कागज़ की नाव, कविता हमें एक नई दुनिया में ले जाती है। 🌈",
  "बीरबल": "बीरबल अपनी चतुराई और हाज़िरजवाबी के लिए जाने जाते थे। उन्होंने सिखाया कि हर मुश्किल सवाल का जवाब बुद्धि और शांति से दिया जा सकता है। 💡",
  "ईमानदारी": "ईमानदारी ही सबसे अच्छी नीति है। जब हमें कोई खोई हुई चीज़ मिलती है, तो उसे उसके असली मालिक तक पहुँचाना ही सच्ची बहादुरी है। ⚽",
  "बचपन": "बचपन सपनों का पिटारा है! कभी हम चौकीदार बनना चाहते हैं तो कभी आइसक्रीम वाला। इन सपनों में ही हमारी कल्पना की उड़ान छिपी है। 🍦",
  "दोस्ती": "सच्ची दोस्ती कपड़ों या पैसों से नहीं, बल्कि दिल से होती है। नसीरुद्दीन और जमाल की कहानी हमें सिखाती है कि दोस्तों के साथ हर पल खास होता है। 🤝",
  "गणित और दया": "दान का मतलब सिर्फ पैसे देना नहीं, बल्कि सही समय पर सही मदद करना है। संन्यासी ने अपनी बुद्धि से राजा को दया और न्याय का पाठ पढ़ाया। 💰",
  "पहेली": "पहेलियाँ हमारे दिमाग की कसरत हैं! 'कौन' कविता में चूहे की शरारतों को पहचानना एक मज़ेदार पहेली सुलझाने जैसा है। 🐭",
  "गांधीजी": "गांधीजी ने हमें अहिंसा और आत्मनिर्भरता का मार्ग दिखाया। साबरमती से दांडी तक की उनकी यात्रा हमारे देश की आज़ादी की एक महत्वपूर्ण कहानी है। 🇮🇳",
  "खेल": "खेल हमें अनुशासन और टीम वर्क सिखाते हैं। 'थप्प रोटी थप्प दाल' खेल में बच्चे रसोई के ज़रिए मिल-जुलकर काम करना सीखते हैं। 🥘",
  "तर्क": "हर बात के पीछे एक 'क्यों' और 'कैसे' होता है। पढ़क्कू की सूझ हमें सिखाती है कि बिना सोचे-समझे किसी बात पर यकीन नहीं करना चाहिए। 🧐",
  "साहस": "साहस का मतलब है अपनी सीमाओं से आगे बढ़ना। सुनीता ने अपनी पहिया कुर्सी को अपनी कमज़ोरी नहीं, बल्कि अपनी ताकत बनाया। ♿",
  "पक्षी": "पक्षी प्रकृति के सुंदर कलाकार हैं। हुदहुद की कलगी और उसकी चोंच उसे सबसे अलग और खास बनाती है। 🐦",
  "लालच": "लालच का फल हमेशा बुरा होता है। भीखूभाई की नारियल की कहानी हमें सिखाती है कि मुफ़्त की चीज़ के चक्कर में हम बड़ी मुसीबत में पड़ सकते हैं। 🥥",

  // --- Kannada entries ---
  "ಕರ್ನಾಟಕ": "ಕನ್ನಡ ನಾಡು ಸುಂದರ ಕಲೆ ಮತ್ತು ಸಂಸ್ಕೃತಿಯ ನೆಲೆಬೀಡು. ನಮ್ಮ ನಾಡಗೀತೆ 'ಜಯ ಭಾರತ ಜನನಿಯ ತನುಜಾತೆ' ಪ್ರತಿಯೊಬ್ಬ ಕನ್ನಡಿಗನ ಹೆಮ್ಮೆ. 🚩",
  "ನಿಸರ್ಗ": "ಪ್ರಕೃತಿಯೇ ನಮಗೆ ಮೊದಲ ಗುರು. ಮರಗಳು, ಹಕ್ಕಿಗಳು ಮತ್ತು ಪ್ರಾಣಿಗಳು ನಮಗೆ ಜೀವನದ ಅಮೂಲ್ಯ ಪಾಠಗಳನ್ನು ಕಲಿಸುತ್ತವೆ. 🌳",
  "ಪರಿಸರ": "ಪರಿಸರ ರಕ್ಷಣೆ ನಮ್ಮೆಲ್ಲರ ಹೊಣೆ. ನಾವು ಗಿಡಗಳನ್ನು ನೆಟ್ಟು, ನೀರನ್ನು ಉಳಿಸಿ ನಮ್ಮ ಭೂಮಿಯನ್ನು ಹಸಿರಾಗಿಡೋಣ. 🌿",
  "ಶಕ್ತಿ": "ಪ್ರತಿ ಮಗುವಿನಲ್ಲೂ ಒಂದು ವಿಶೇಷ ಶಕ್ತಿಯಿದೆ. ಸತತ ಪ್ರಯತ್ನ ಮತ್ತು ಆತ್ಮವಿಶ್ವಾಸದಿಂದ ನಾವು ಎಂತಹ ಕಷ್ಟದ ಗುರಿಯನ್ನಾದರೂ ಸಾಧಿಸಬಹುದು. 💪",
  "ಕತೆ": "ಕತೆಗಳು ಜ್ಞಾನದ ಕಿಟಕಿಗಳು. ಅಜ್ಜಿ ಹೇಳುವ ಕತೆಗಳಿಂದ ಹಿಡಿದು ಪುಸ್ತಕದ ಕತೆಗಳವರೆಗೆ ಪ್ರತಿಯೊಂದೂ ನಮಗೆ ಹೊಸ ವಿಚಾರಗಳನ್ನು ತಿಳಿಸುತ್ತವೆ. 📚",
  "ಸಾಮರಸ್ಯ": "ಎಲ್ಲರೂ ಒಂದಾಗಿ ಬಾಳುವುದೇ ಜೀವನದ ಸೌಂದರ್ಯ. ವಿವಿಧ ಧರ್ಮ ಮತ್ತು ಭಾಷೆಗಳ ಜನರು ಸಾಮರಸ್ಯದಿಂದ ಬದುಕುವುದೇ ನಮ್ಮ ನಾಡಿನ ಹಿರಿಮೆ. 🤝",

  // --- General Subject Fallbacks ---
  "mathematics": "Math is the language of the universe! From the patterns on a tiger's skin to the orbits of the planets, everything follows mathematical rules. Let's solve some mysteries! 🔢",
  "science": "EVS helps us understand the amazing world around us — from the tiniest ant to the giant elephant. Nature is the best teacher! 🌿",
  "hindi": "हिन्दी हमारी शान है! कहानियों और कविताओं के ज़रिए हम अपनी संस्कृति और मूल्यों को सीखते हैं। चलिए, शब्दों के सफर पर चलते हैं! 📝",
  "english": "English is a window to the world! It helps us share our ideas with people everywhere. Let's read, write, and dream in English! 📖",
  "kannada": "ಕನ್ನಡ ಅಚ್ಚುಮೆಚ್ಚಿನ ಭಾಷೆ! ನಮ್ಮ ನಾಡು, ನುಡಿ ಮತ್ತು ಸಂಸ್ಕೃತಿಯ ಬಗ್ಗೆ ತಿಳಿಯೋಣ. 🚩",
  "computers": "Computers are magic boxes that follow our commands! Learning how they work is like learning a secret superpower for the future. 💻"
};
